name: save_it
description: SaveIt Application.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1-80.1.beta <3.0.0"

dependencies:
  animated_text_kit: ^4.2.1
  clipboard: ^0.1.3
  cloud_firestore: ^3.1.10
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  firebase_auth: ^3.3.9
  firebase_core: ^1.13.1
  flutter:
    sdk: flutter
  flutter_custom_carousel_slider: ^1.2.0
  font_awesome_flutter: ^9.2.0
  get: ^4.6.1
  get_storage: ^2.0.3
  http: ^0.13.4
  intl: ^0.17.0
  introduction_screen: ^3.0.0
  news_api_flutter_package: ^1.1.0
  persistent_bottom_nav_bar: ^4.0.2
  plaid_flutter: ^2.2.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  lint: ^1.8.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Nunito-Black.ttf
          weight: 900
