name: save_it
description: SaveIt Application.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1-80.1.beta <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  flutter:
    sdk: flutter
  font_awesome_flutter: ^9.2.0
  get: ^4.6.1
  get_storage: ^2.0.3
  http: ^0.13.4
  intl: ^0.17.0
  persistent_bottom_nav_bar: ^4.0.2
  plaid_flutter: ^2.2.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  lint: ^1.8.1

flutter:
  uses-material-design: true
